from setuptools import setup

setup(
    name='NVOtest',
    version='',
    packages=['hsvenv.Lib.site-packages.bs4', 'hsvenv.Lib.site-packages.bs4.tests',
              'hsvenv.Lib.site-packages.bs4.builder', 'hsvenv.Lib.site-packages.rsa', 'hsvenv.Lib.site-packages.cffi',
              'hsvenv.Lib.site-packages.idna', 'hsvenv.Lib.site-packages.pytz', 'hsvenv.Lib.site-packages.Crypto',
              'hsvenv.Lib.site-packages.Crypto.IO', 'hsvenv.Lib.site-packages.Crypto.Hash',
              'hsvenv.Lib.site-packages.Crypto.Math', 'hsvenv.Lib.site-packages.Crypto.Util',
              'hsvenv.Lib.site-packages.Crypto.Cipher', 'hsvenv.Lib.site-packages.Crypto.Random',
              'hsvenv.Lib.site-packages.Crypto.Protocol', 'hsvenv.Lib.site-packages.Crypto.SelfTest',
              'hsvenv.Lib.site-packages.Crypto.SelfTest.IO', 'hsvenv.Lib.site-packages.Crypto.SelfTest.Hash',
              'hsvenv.Lib.site-packages.Crypto.SelfTest.Math', 'hsvenv.Lib.site-packages.Crypto.SelfTest.Util',
              'hsvenv.Lib.site-packages.Crypto.SelfTest.Cipher', 'hsvenv.Lib.site-packages.Crypto.SelfTest.Random',
              'hsvenv.Lib.site-packages.Crypto.SelfTest.Protocol', 'hsvenv.Lib.site-packages.Crypto.SelfTest.PublicKey',
              'hsvenv.Lib.site-packages.Crypto.SelfTest.Signature', 'hsvenv.Lib.site-packages.Crypto.PublicKey',
              'hsvenv.Lib.site-packages.Crypto.Signature', 'hsvenv.Lib.site-packages.jinja2',
              'hsvenv.Lib.site-packages.pyasn1', 'hsvenv.Lib.site-packages.pyasn1.type',
              'hsvenv.Lib.site-packages.pyasn1.codec', 'hsvenv.Lib.site-packages.pyasn1.codec.ber',
              'hsvenv.Lib.site-packages.pyasn1.codec.cer', 'hsvenv.Lib.site-packages.pyasn1.codec.der',
              'hsvenv.Lib.site-packages.pyasn1.codec.native', 'hsvenv.Lib.site-packages.pyasn1.compat',
              'hsvenv.Lib.site-packages.certifi', 'hsvenv.Lib.site-packages.chardet',
              'hsvenv.Lib.site-packages.chardet.cli', 'hsvenv.Lib.site-packages.OpenSSL',
              'hsvenv.Lib.site-packages.tzlocal', 'hsvenv.Lib.site-packages.urllib3',
              'hsvenv.Lib.site-packages.urllib3.util', 'hsvenv.Lib.site-packages.urllib3.contrib',
              'hsvenv.Lib.site-packages.urllib3.contrib._securetransport', 'hsvenv.Lib.site-packages.urllib3.packages',
              'hsvenv.Lib.site-packages.urllib3.packages.backports',
              'hsvenv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'hsvenv.Lib.site-packages.M2Crypto',
              'hsvenv.Lib.site-packages.M2Crypto.PGP', 'hsvenv.Lib.site-packages.M2Crypto.SSL',
              'hsvenv.Lib.site-packages.requests', 'hsvenv.Lib.site-packages.pycparser',
              'hsvenv.Lib.site-packages.pycparser.ply', 'hsvenv.Lib.site-packages.asn1crypto',
              'hsvenv.Lib.site-packages.asn1crypto._perf', 'hsvenv.Lib.site-packages.markupsafe',
              'hsvenv.Lib.site-packages.cryptography', 'hsvenv.Lib.site-packages.cryptography.x509',
              'hsvenv.Lib.site-packages.cryptography.hazmat', 'hsvenv.Lib.site-packages.cryptography.hazmat.backends',
              'hsvenv.Lib.site-packages.cryptography.hazmat.backends.openssl',
              'hsvenv.Lib.site-packages.cryptography.hazmat.bindings',
              'hsvenv.Lib.site-packages.cryptography.hazmat.bindings.openssl',
              'hsvenv.Lib.site-packages.cryptography.hazmat.primitives',
              'hsvenv.Lib.site-packages.cryptography.hazmat.primitives.kdf',
              'hsvenv.Lib.site-packages.cryptography.hazmat.primitives.ciphers',
              'hsvenv.Lib.site-packages.cryptography.hazmat.primitives.twofactor',
              'hsvenv.Lib.site-packages.cryptography.hazmat.primitives.asymmetric',
              'hsvenv.Lib.site-packages.pyinstaller_hooks', 'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip.req',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip.vcs',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip.utils',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip.compat',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip.models',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.distlib',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.distlib._backport',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.colorama',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.html5lib',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.html5lib._trie',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.html5lib.filters',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.html5lib.treewalkers',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.html5lib.treeadapters',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.html5lib.treebuilders',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.lockfile',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.progress',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.requests',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.requests.packages',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.requests.packages.chardet',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.requests.packages.urllib3',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.requests.packages.urllib3.util',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.requests.packages.urllib3.contrib',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.requests.packages.urllib3.packages',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.packaging',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.cachecontrol',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.cachecontrol.caches',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.webencodings',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip._vendor.pkg_resources',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip.commands',
              'hsvenv.Lib.site-packages.pip-9.0.1-py3.4.egg.pip.operations',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.Hash',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.Util',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.Cipher',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.Random',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.Random.OSRNG',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.Random.Fortuna',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.Protocol',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.SelfTest',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.SelfTest.Hash',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.SelfTest.Util',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.SelfTest.Cipher',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.SelfTest.Random',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.SelfTest.Random.OSRNG',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.SelfTest.Random.Fortuna',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.SelfTest.Protocol',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.SelfTest.PublicKey',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.SelfTest.Signature',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.PublicKey',
              'hsvenv.Lib.site-packages.pycrypto-2.6.1-py3.4-win-amd64.egg.Crypto.Signature'],
    url='',
    license='',
    author='hsousa',
    author_email='',
    description=''
)
